"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShipMountDepositsEnum = exports.ShipMountSymbolEnum = void 0;
exports.ShipMountSymbolEnum = {
    GasSiphonI: 'MOUNT_GAS_SIPHON_I',
    GasSiphonIi: 'MOUNT_GAS_SIPHON_II',
    GasSiphonIii: 'MOUNT_GAS_SIPHON_III',
    SurveyorI: 'MOUNT_SURVEYOR_I',
    SurveyorIi: 'MOUNT_SURVEYOR_II',
    SurveyorIii: 'MOUNT_SURVEYOR_III',
    SensorArrayI: 'MOUNT_SENSOR_ARRAY_I',
    SensorArrayIi: 'MOUNT_SENSOR_ARRAY_II',
    SensorArrayIii: 'MOUNT_SENSOR_ARRAY_III',
    MiningLaserI: 'MOUNT_MINING_LASER_I',
    MiningLaserIi: 'MOUNT_MINING_LASER_II',
    MiningLaserIii: 'MOUNT_MINING_LASER_III',
    LaserCannonI: 'MOUNT_LASER_CANNON_I',
    MissileLauncherI: 'MOUNT_MISSILE_LAUNCHER_I',
    TurretI: 'MOUNT_TURRET_I'
};
exports.ShipMountDepositsEnum = {
    QuartzSand: 'QUARTZ_SAND',
    SiliconCrystals: 'SILICON_CRYSTALS',
    PreciousStones: 'PRECIOUS_STONES',
    IceWater: 'ICE_WATER',
    AmmoniaIce: 'AMMONIA_ICE',
    IronOre: 'IRON_ORE',
    CopperOre: 'COPPER_ORE',
    SilverOre: 'SILVER_ORE',
    AluminumOre: 'ALUMINUM_ORE',
    GoldOre: 'GOLD_ORE',
    PlatinumOre: 'PLATINUM_ORE',
    Diamonds: 'DIAMONDS',
    UraniteOre: 'URANITE_ORE',
    MeritiumOre: 'MERITIUM_ORE'
};
//# sourceMappingURL=ship-mount.js.map