/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipRequirements } from './ship-requirements';
/**
 * A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
 * @export
 * @interface ShipModule
 */
export interface ShipModule {
    /**
     *
     * @type {string}
     * @memberof ShipModule
     */
    'symbol': ShipModuleSymbolEnum;
    /**
     *
     * @type {number}
     * @memberof ShipModule
     */
    'capacity'?: number;
    /**
     *
     * @type {number}
     * @memberof ShipModule
     */
    'range'?: number;
    /**
     *
     * @type {string}
     * @memberof ShipModule
     */
    'name': string;
    /**
     *
     * @type {string}
     * @memberof ShipModule
     */
    'description'?: string;
    /**
     *
     * @type {ShipRequirements}
     * @memberof ShipModule
     */
    'requirements': ShipRequirements;
}
export declare const ShipModuleSymbolEnum: {
    readonly MineralProcessorI: "MODULE_MINERAL_PROCESSOR_I";
    readonly CargoHoldI: "MODULE_CARGO_HOLD_I";
    readonly CrewQuartersI: "MODULE_CREW_QUARTERS_I";
    readonly EnvoyQuartersI: "MODULE_ENVOY_QUARTERS_I";
    readonly PassengerCabinI: "MODULE_PASSENGER_CABIN_I";
    readonly MicroRefineryI: "MODULE_MICRO_REFINERY_I";
    readonly OreRefineryI: "MODULE_ORE_REFINERY_I";
    readonly FuelRefineryI: "MODULE_FUEL_REFINERY_I";
    readonly ScienceLabI: "MODULE_SCIENCE_LAB_I";
    readonly JumpDriveI: "MODULE_JUMP_DRIVE_I";
    readonly JumpDriveIi: "MODULE_JUMP_DRIVE_II";
    readonly JumpDriveIii: "MODULE_JUMP_DRIVE_III";
    readonly WarpDriveI: "MODULE_WARP_DRIVE_I";
    readonly WarpDriveIi: "MODULE_WARP_DRIVE_II";
    readonly WarpDriveIii: "MODULE_WARP_DRIVE_III";
    readonly ShieldGeneratorI: "MODULE_SHIELD_GENERATOR_I";
    readonly ShieldGeneratorIi: "MODULE_SHIELD_GENERATOR_II";
};
export declare type ShipModuleSymbolEnum = typeof ShipModuleSymbolEnum[keyof typeof ShipModuleSymbolEnum];
//# sourceMappingURL=ship-module.d.ts.map