/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WaypointTrait
 */
export interface WaypointTrait {
    /**
     * The unique identifier of the trait.
     * @type {string}
     * @memberof WaypointTrait
     */
    'symbol': WaypointTraitSymbolEnum;
    /**
     * The name of the trait.
     * @type {string}
     * @memberof WaypointTrait
     */
    'name': string;
    /**
     * A description of the trait.
     * @type {string}
     * @memberof WaypointTrait
     */
    'description': string;
}
export declare const WaypointTraitSymbolEnum: {
    readonly Uncharted: "UNCHARTED";
    readonly Marketplace: "MARKETPLACE";
    readonly Shipyard: "SHIPYARD";
    readonly Outpost: "OUTPOST";
    readonly ScatteredSettlements: "SCATTERED_SETTLEMENTS";
    readonly SprawlingCities: "SPRAWLING_CITIES";
    readonly MegaStructures: "MEGA_STRUCTURES";
    readonly Overcrowded: "OVERCROWDED";
    readonly HighTech: "HIGH_TECH";
    readonly Corrupt: "CORRUPT";
    readonly Bureaucratic: "BUREAUCRATIC";
    readonly TradingHub: "TRADING_HUB";
    readonly Industrial: "INDUSTRIAL";
    readonly BlackMarket: "BLACK_MARKET";
    readonly ResearchFacility: "RESEARCH_FACILITY";
    readonly MilitaryBase: "MILITARY_BASE";
    readonly SurveillanceOutpost: "SURVEILLANCE_OUTPOST";
    readonly ExplorationOutpost: "EXPLORATION_OUTPOST";
    readonly MineralDeposits: "MINERAL_DEPOSITS";
    readonly CommonMetalDeposits: "COMMON_METAL_DEPOSITS";
    readonly PreciousMetalDeposits: "PRECIOUS_METAL_DEPOSITS";
    readonly RareMetalDeposits: "RARE_METAL_DEPOSITS";
    readonly MethanePools: "METHANE_POOLS";
    readonly IceCrystals: "ICE_CRYSTALS";
    readonly ExplosiveGases: "EXPLOSIVE_GASES";
    readonly StrongMagnetosphere: "STRONG_MAGNETOSPHERE";
    readonly VibrantAuroras: "VIBRANT_AURORAS";
    readonly SaltFlats: "SALT_FLATS";
    readonly Canyons: "CANYONS";
    readonly PerpetualDaylight: "PERPETUAL_DAYLIGHT";
    readonly PerpetualOvercast: "PERPETUAL_OVERCAST";
    readonly DrySeabeds: "DRY_SEABEDS";
    readonly MagmaSeas: "MAGMA_SEAS";
    readonly Supervolcanoes: "SUPERVOLCANOES";
    readonly AshClouds: "ASH_CLOUDS";
    readonly VastRuins: "VAST_RUINS";
    readonly MutatedFlora: "MUTATED_FLORA";
    readonly Terraformed: "TERRAFORMED";
    readonly ExtremeTemperatures: "EXTREME_TEMPERATURES";
    readonly ExtremePressure: "EXTREME_PRESSURE";
    readonly DiverseLife: "DIVERSE_LIFE";
    readonly ScarceLife: "SCARCE_LIFE";
    readonly Fossils: "FOSSILS";
    readonly WeakGravity: "WEAK_GRAVITY";
    readonly StrongGravity: "STRONG_GRAVITY";
    readonly CrushingGravity: "CRUSHING_GRAVITY";
    readonly ToxicAtmosphere: "TOXIC_ATMOSPHERE";
    readonly CorrosiveAtmosphere: "CORROSIVE_ATMOSPHERE";
    readonly BreathableAtmosphere: "BREATHABLE_ATMOSPHERE";
    readonly Jovian: "JOVIAN";
    readonly Rocky: "ROCKY";
    readonly Volcanic: "VOLCANIC";
    readonly Frozen: "FROZEN";
    readonly Swamp: "SWAMP";
    readonly Barren: "BARREN";
    readonly Temperate: "TEMPERATE";
    readonly Jungle: "JUNGLE";
    readonly Ocean: "OCEAN";
    readonly Stripped: "STRIPPED";
};
export declare type WaypointTraitSymbolEnum = typeof WaypointTraitSymbolEnum[keyof typeof WaypointTraitSymbolEnum];
//# sourceMappingURL=waypoint-trait.d.ts.map