"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentsApi = exports.AgentsApiFactory = exports.AgentsApiFp = exports.AgentsApiAxiosParamCreator = void 0;
const axios_1 = __importDefault(require("axios"));
// Some imports not used depending on template conditions
// @ts-ignore
const common_1 = require("../common");
// @ts-ignore
const base_1 = require("../base");
/**
 * AgentsApi - axios parameter creator
 * @export
 */
const AgentsApiAxiosParamCreator = function (configuration) {
    return {
        /**
         * Fetch your agent\'s details.
         * @summary My Agent Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyAgent: (options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/my/agent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication AgentToken required
            // http bearer authentication required
            yield common_1.setBearerAuthToObject(localVarHeaderParameter, configuration);
            common_1.setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: common_1.toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
    };
};
exports.AgentsApiAxiosParamCreator = AgentsApiAxiosParamCreator;
/**
 * AgentsApi - functional programming interface
 * @export
 */
const AgentsApiFp = function (configuration) {
    const localVarAxiosParamCreator = exports.AgentsApiAxiosParamCreator(configuration);
    return {
        /**
         * Fetch your agent\'s details.
         * @summary My Agent Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyAgent(options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.getMyAgent(options);
                return common_1.createRequestFunction(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration);
            });
        },
    };
};
exports.AgentsApiFp = AgentsApiFp;
/**
 * AgentsApi - factory interface
 * @export
 */
const AgentsApiFactory = function (configuration, basePath, axios) {
    const localVarFp = exports.AgentsApiFp(configuration);
    return {
        /**
         * Fetch your agent\'s details.
         * @summary My Agent Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyAgent(options) {
            return localVarFp.getMyAgent(options).then((request) => request(axios, basePath));
        },
    };
};
exports.AgentsApiFactory = AgentsApiFactory;
/**
 * AgentsApi - object-oriented interface
 * @export
 * @class AgentsApi
 * @extends {BaseAPI}
 */
class AgentsApi extends base_1.BaseAPI {
    /**
     * Fetch your agent\'s details.
     * @summary My Agent Details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentsApi
     */
    getMyAgent(options) {
        return exports.AgentsApiFp(this.configuration).getMyAgent(options).then((request) => request(this.axios, this.basePath));
    }
}
exports.AgentsApi = AgentsApi;
//# sourceMappingURL=agents-api.js.map