/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { AcceptContract200Response } from '../models';
import { DeliverContract200Response } from '../models';
import { DeliverContractRequest } from '../models';
import { FulfillContract200Response } from '../models';
import { GetContract200Response } from '../models';
import { GetContracts200Response } from '../models';
/**
 * ContractsApi - axios parameter creator
 * @export
 */
export declare const ContractsApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     * Accept a contract.
     * @summary Accept Contract
     * @param {string} contractId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    acceptContract: (contractId: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Deliver cargo on a given contract.
     * @summary Deliver Contract
     * @param {string} contractId The ID of the contract
     * @param {DeliverContractRequest} [deliverContractRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deliverContract: (contractId: string, deliverContractRequest?: DeliverContractRequest | undefined, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Fulfill a contract
     * @summary Fulfill Contract
     * @param {string} contractId The ID of the contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    fulfillContract: (contractId: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Get the details of a contract by ID.
     * @summary Get Contract
     * @param {string} contractId The contract ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContract: (contractId: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * List all of your contracts.
     * @summary List Contracts
     * @param {number} [page] What entry offset to request
     * @param {number} [limit] How many entries to return per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContracts: (page?: number | undefined, limit?: number | undefined, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * ContractsApi - functional programming interface
 * @export
 */
export declare const ContractsApiFp: (configuration?: Configuration | undefined) => {
    /**
     * Accept a contract.
     * @summary Accept Contract
     * @param {string} contractId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    acceptContract(contractId: string, options?: AxiosRequestConfig<any> | undefined): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<AcceptContract200Response>>;
    /**
     * Deliver cargo on a given contract.
     * @summary Deliver Contract
     * @param {string} contractId The ID of the contract
     * @param {DeliverContractRequest} [deliverContractRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deliverContract(contractId: string, deliverContractRequest?: DeliverContractRequest | undefined, options?: AxiosRequestConfig<any> | undefined): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<DeliverContract200Response>>;
    /**
     * Fulfill a contract
     * @summary Fulfill Contract
     * @param {string} contractId The ID of the contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    fulfillContract(contractId: string, options?: AxiosRequestConfig<any> | undefined): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<FulfillContract200Response>>;
    /**
     * Get the details of a contract by ID.
     * @summary Get Contract
     * @param {string} contractId The contract ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContract(contractId: string, options?: AxiosRequestConfig<any> | undefined): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<GetContract200Response>>;
    /**
     * List all of your contracts.
     * @summary List Contracts
     * @param {number} [page] What entry offset to request
     * @param {number} [limit] How many entries to return per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContracts(page?: number | undefined, limit?: number | undefined, options?: AxiosRequestConfig<any> | undefined): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<GetContracts200Response>>;
};
/**
 * ContractsApi - factory interface
 * @export
 */
export declare const ContractsApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     * Accept a contract.
     * @summary Accept Contract
     * @param {string} contractId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    acceptContract(contractId: string, options?: any): AxiosPromise<AcceptContract200Response>;
    /**
     * Deliver cargo on a given contract.
     * @summary Deliver Contract
     * @param {string} contractId The ID of the contract
     * @param {DeliverContractRequest} [deliverContractRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deliverContract(contractId: string, deliverContractRequest?: DeliverContractRequest | undefined, options?: any): AxiosPromise<DeliverContract200Response>;
    /**
     * Fulfill a contract
     * @summary Fulfill Contract
     * @param {string} contractId The ID of the contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    fulfillContract(contractId: string, options?: any): AxiosPromise<FulfillContract200Response>;
    /**
     * Get the details of a contract by ID.
     * @summary Get Contract
     * @param {string} contractId The contract ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContract(contractId: string, options?: any): AxiosPromise<GetContract200Response>;
    /**
     * List all of your contracts.
     * @summary List Contracts
     * @param {number} [page] What entry offset to request
     * @param {number} [limit] How many entries to return per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContracts(page?: number | undefined, limit?: number | undefined, options?: any): AxiosPromise<GetContracts200Response>;
};
/**
 * ContractsApi - object-oriented interface
 * @export
 * @class ContractsApi
 * @extends {BaseAPI}
 */
export declare class ContractsApi extends BaseAPI {
    /**
     * Accept a contract.
     * @summary Accept Contract
     * @param {string} contractId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractsApi
     */
    acceptContract(contractId: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<AcceptContract200Response, any>>;
    /**
     * Deliver cargo on a given contract.
     * @summary Deliver Contract
     * @param {string} contractId The ID of the contract
     * @param {DeliverContractRequest} [deliverContractRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractsApi
     */
    deliverContract(contractId: string, deliverContractRequest?: DeliverContractRequest, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<DeliverContract200Response, any>>;
    /**
     * Fulfill a contract
     * @summary Fulfill Contract
     * @param {string} contractId The ID of the contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractsApi
     */
    fulfillContract(contractId: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<FulfillContract200Response, any>>;
    /**
     * Get the details of a contract by ID.
     * @summary Get Contract
     * @param {string} contractId The contract ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractsApi
     */
    getContract(contractId: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<GetContract200Response, any>>;
    /**
     * List all of your contracts.
     * @summary List Contracts
     * @param {number} [page] What entry offset to request
     * @param {number} [limit] How many entries to return per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContractsApi
     */
    getContracts(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<GetContracts200Response, any>>;
}
//# sourceMappingURL=contracts-api.d.ts.map